kind: Deployment
apiVersion: extensions/v1beta1
metadata: 
  name: frontend
  namespace: default
  labels: 
    run: frontend
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      run: frontend
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/capstone-project-team2/frontend:v1
          ports:
            - containerPort: 3000
              protocol: TCP

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata: 
  name: backend
  namespace: default
  labels: 
    run: backend
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      run: backend
  template:
    metadata:
      labels:
        run: backend
    spec: 
      containers:
        - name: backend
          image: gcr.io/capstone-project-team2/backend:v1
          ports:
            - containerPort: 8000
              protocol: TCP

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata: 
  name: database
  namespace: default
  labels: 
    run: database
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      run: database
  template: 
    metadata: 
      labels: 
        run: database
    spec: 
      containers: 
        - name: database
          image: gcr.io/capstone-project-team2/database:v1
          ports: 
            - containerPort: 5432
              protocol: TCP