apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: ingress
  namespace: default
spec:
  rules:
    - host: frontend.trippplanner.com
      http:
        paths:
          - backend:
              serviceName: frontend
              servicePort: 80
            path: /
    - host: backend.trippplanner.com
      http:
        paths:
          - backend:
              serviceName: backend
              servicePort: 8000
            path: /
    - host: database.trippplanner.com
      http:
        paths:
          - backend:
              serviceName: database
              servicePort: 5432
            path: / 
  tls:
    - hosts:
        - frontend.trippplanner.com
        - backend.trippplanner.com
        - database.trippplanner.com
      secretName: ssl-certs