FROM mongo:latest

EXPOSE 27017

#TODO: You can seed it this way if required
# COPY init.json /init.json
# CMD mongoimport --db itinerary --collection MyDummyCollection --type json --file /init.json --jsonArray