# Generated by Django 2.2.6 on 2019-11-07 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_service', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(through='member_service.UserToGroup', to='member_service.User'),
        ),
        migrations.AlterField(
            model_name='usertogroup',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='member_service.User'),
        ),
    ]
