#!/bin/bash
export PROJECT=capstone-project-team2
export CLUSTER=capstone-team2-cluster
export ZONE=us-west1-b
export GCR_REGISTRY=gcr.io
export FRONTEND_DOCKER_IMG=frontend
export BACKEND_DOCKER_IMG=backend
export DATABASE_DOCKER_IMG=database
export SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=imYZVVJY8HF6jXFVKwEALwAH
export SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=117123737084-rp4gfof0cf77kqjm65j69upudlefshsj.apps.googleusercontent.com
export YELP_API_KEY=MB_TUAI96_WP-B2XJl6S06raCPLAKzrJdJXd1kXgngCQMEJrjy-ubXDALP7Xd1yaQv0ArIjgna1zah1R2iXEHqFHC_yVjFlDwKpbc5v5EDWl3nbZGU0E3_tNtC-_XXYx
export GOOGLE_API_KEY=AIzaSyB6YgxpNCFRclsxCFIY8hGU1508sLVzxKY
export REACT_APP_ENVIRONMENT=dev